# -*- coding: utf-8 -*-
"""converting shapefiles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VR4j5G_i5VLUCUO4UnByX6TmuNcqG4hV
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time 
# 
# # Important library for many geopython libraries
# !apt install gdal-bin python-gdal python3-gdal 
# # Install rtree - Geopandas requirment
# !apt install python3-rtree 
# # Install Geopandas
# !pip install git+git://github.com/geopandas/geopandas.git
# # Install descartes - Geopandas requirment
# !pip install descartes 
# # Install Folium for Geographic data visualization
# !pip install folium
# # Install plotlyExpress
# !pip install plotly_expressl geopandas

import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point
import matplotlib
import matplotlib.pyplot as plt 
import folium

shapefile1 = "/content/UK_LAD_2019.shp"

lad19 = gpd.read_file(shapefile1) 
lad19.head()

lad19.crs

lad19["geometry"].head()

lad19.to_crs({'init': 'epsg:4326'},inplace=True) 
lad19.crs

lad19["geometry"].head()

lad19.to_file("LTLA_2019.shp")
